version: 1

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: generic
    level: DEBUG

formatters:
  generic:
    format: "%(asctime)s %(levelname)-5.5s [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S %z"

loggers:
  maplocate: {}

  aiohttp:
    level: INFO
    handlers:
    - console

root:
  level: INFO
  handlers:
  - console

